AWSTemplateFormatVersion: '2010-09-09'
Description: 'Foundation layer for Epic monitoring - Member Account Deployment'

Parameters:
  Environment:
    Type: String
    Description: 'Environment name (prod/nonprod/shared/train/readonly)'
    AllowedValues: ['prod', 'nonprod', 'shared','train','readonly']
    Default: 'prod'
  ProjectName:
    Type: String
    Description: 'Project name for resource tagging'
    Default: 'Epic'
  NotificationEmail:
    Type: String
    Description: 'Email address for SNS notifications'

Resources:
  MonitoringSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-Monitoring-${Environment}-${AWS::StackName}'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics: 
        - !Ref MonitoringSNSTopic
      PolicyDocument:
        Id: !Sub "${ProjectName}TopicPolicy"
        Version: '2012-10-17'
        Statement:
          - Sid: "AllowCloudWatchPublish"
            Effect: "Allow"
            Principal:
              Service: "cloudwatch.amazonaws.com"
            Action: "sns:Publish"
            Resource: !GetAtt MonitoringSNSTopic.TopicArn
          - Sid: "AllowEventsPublish"
            Effect: "Allow"
            Principal:
              Service: "events.amazonaws.com"
            Action: "sns:Publish"
            Resource: !GetAtt MonitoringSNSTopic.TopicArn

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref MonitoringSNSTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

Outputs:
  SNSTopicArn:
    Description: 'ARN of the SNS Topic'
    Value: !Ref MonitoringSNSTopic
    Export:
      Name: !Sub '${ProjectName}-SNSTopic-${Environment}-${AWS::StackName}'

  SNSTopicName:
    Description: 'Name of the SNS Topic'
    Value: !GetAtt MonitoringSNSTopic.TopicName
    Export:
      Name: !Sub '${ProjectName}-SNSTopicName-${Environment}-${AWS::StackName}'
