AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Roles for Epic Monitoring'

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name for resource tagging'
    Default: 'Epic'
  Environment:
    Type: String
    Description: 'Environment name'
    AllowedValues: 
      - prod
      - nonprod
      - shared
      - train
      - readonly
    Default: 'prod'

Resources:
  MonitoringLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'Epic-Mon-${Environment}-${AWS::AccountId}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: !Sub 'Epic-Mon-Policy-${Environment}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  # CloudWatch Permissions
                  - 'cloudwatch:PutMetricAlarm'
                  - 'cloudwatch:DeleteAlarms'
                  - 'cloudwatch:DescribeAlarms'
                  - 'cloudwatch:GetMetricStatistics'
                  
                  # EC2 Related Permissions
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeVolumes'
                  - 'ec2:DescribeVpnConnections'
                  - 'ec2:DescribeTransitGateways'
                  
                  # Load Balancer Permissions
                  - 'elasticloadbalancing:DescribeLoadBalancers'
                  - 'elasticloadbalancing:DescribeTargetGroups'
                  - 'elasticloadbalancing:DescribeTargetHealth'
                  
                  # RDS Permissions
                  - 'rds:DescribeDBInstances'
                  - 'rds:DescribeDBClusters'
                  
                  # Direct Connect Permissions
                  - 'directconnect:DescribeConnections'
                  
                  # WAF Permissions
                  - 'wafv2:ListWebACLs'
                  - 'wafv2:GetWebACL'
                  
                  # Network Firewall Permissions
                  - 'network-firewall:ListFirewalls'
                  - 'network-firewall:DescribeFirewall'
                  
                  # FSx Permissions
                  - 'fsx:DescribeFileSystems'
                  
                  # SNS Permissions
                  - 'sns:Publish'
                  - 'sns:ListTopics'
                  
                  # CloudWatch Logs Permissions
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  
                  # Additional Permissions for Enhanced Monitoring
                  - 'cloudwatch:GetMetricData'
                  - 'cloudwatch:ListMetrics'
                Resource: '*'
              
              # Optional: You can restrict resources by adding specific ARNs
              - Effect: Allow
                Action:
                  - 'sns:Publish'
                Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${ProjectName}-Monitoring-${Environment}'

Outputs:
  MonitoringRoleArn:
    Description: 'ARN of the Monitoring Lambda Role'
    Value: !GetAtt MonitoringLambdaRole.Arn
    Export:
      Name: !Sub '${ProjectName}-MonRole-${Environment}'
